name: ASP.NET CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-laters
    
    steps:
    - uses: actions/checkout@master
    - name: Setting up Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Nuget Push
      run: nuget push *.nupkg
