name: Publish NuGet

# Trigger a publish to Nuget when a commit is pushed to master.
on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
 

    - uses: actions/checkout@master
    - name: Setting up Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Nuget Build
      run: nuget pack Orcabot-Shared-Types.csproj

    - name: Nuget Push
      run: nuget push *.nupkg
           # Change this to fit the Repository
      
