name: Publish NuGet

# Trigger a publish to Nuget when a commit is pushed to master.
on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
 

    - uses: actions/checkout@master
    - name: Setting up Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Build the project with dotnet
      uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.0' # SDK Version to use.
          
    - name: Build dotnet project
      run: dotnet build Orcabot-Shared-Types\Orcabot-Shared-Types.csproj
      
    - name: Display tree
      run: dir
      
    - name: Nuget Build
      run: nuget pack Orcabot-Shared-Types\Orcabot-Shared-Types.csproj

    - name: Nuget Push
      run: nuget push Orcabot-Shared-Types\*.nupkg
